## YAML Template.
---
fos_user_registration_register:
    path: /rejestracja
    defaults:
        _controller: App\Controller\RegistrationController::registerAction
        
fos_user_security_login:
    path: /logowanie
    defaults:
        _controller: App\Controller\SecurityController::loginAction