## YAML Template.
---
homepage:
    path:     /
    controller: App\Controller\HomePageController::index

app_my_account:
    path:     /moje-konto
    controller: App\Controller\AccountController::myAccountAction
