## YAML Template.
---
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     App\Application\Sonata\UserBundle\Entity\User

    service:
        user_manager: sonata.user.orm.user_manager
        
    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    

    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
        
    