#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
    
fos_user: 
     resource: "@FOSUserBundle/Resources/config/routing/all.xml" 
     
     
