# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    mailer_user: mateuszstr1994@gmail.com
    database_host: 127.0.0.1
    database_port: null
    database_name: najemiwynajem
    database_user: root
    database_password: null
    sonata.page.admin.site.class: App\Application\Sonata\PageBundle\Admin\SiteAdmin
    sonata.page.route.page.generator.class: App\Application\Sonata\PageBundle\Route\RoutePageGenerator

imports:
    - { resource: '../src/Resources/services/block.yml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.menu:
        class: App\Admin\MenuAdmin
        arguments: [~, App\Entity\Main\Menu, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Menu, label: Menu, icon: "<i class=\"mr-2 fas  fa-bars\"></i>" }
        public: true

    admin.menu_item:
        class: App\Admin\MenuItemAdmin
        arguments: [~, App\Entity\Main\MenuItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Menu, label: MenuItem, icon: "<i class=\"mr-2 fas fa-bars\"></i>" }
        public: true

    admin.country:
        class: App\Admin\CountryAdmin
        arguments: [~, App\Entity\Main\Country, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Settings, label: Country, icon: "<i class=\"mr-2 fas fa-cogs\"></i>" }
        public: true

    admin.people:
        class: App\Admin\PeopleAdmin
        arguments: [~, App\Entity\Main\People, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: People, label: People, icon: "<i class=\"mr-2 fa fa-users\"></i>" }
        public: true
        
        
    App\Controller\RegistrationController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
            
    app.validation.service:
        class: App\Service\ValidationService
        arguments: [ "@doctrine.orm.entity_manager",  '@service_container' ]
        public: true
