<?php

namespace App\Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Person;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User extends BaseUser
{
    
    const USER_VALIDATION = [
        'registration_fields' => [
            'username' => [
                'type' => 'string',
                'min' => '5',
                'max' => '10'
            ]
        ]
    ];
    
    /**
     * @var int $id
     */
    protected $id;
    
    protected $person;
   
    protected $email;
    
    public function getId()
    {
        return $this->id;
    }
    
//    # uzytkownik awsze bedzie miał swój profil
//    public function __construct()
//    {
//      // $this->people = new People($this);
//    }
    
    function getPerson() {
        return $this->person;
    }

    function setPerson($person) {
        $this->person = $person;
    }
    
    function getEmail() {
        return $this->email;
    }

    function getEmailCanonical() {
        return $this->emailCanonical;
    }

    function setEmail($email) {
        $this->email = $email;
    }
    
    function getPassword() {
        return $this->password;
    }

    function setPassword($password) {
        $this->password = $password;
    }

    function setPlainPassword($plainPassword) {
        $this->plainPassword = $plainPassword;
    }
    
    function set($key, $value) {
        $this->$key = $value;
    }
    
}
